### ISSUE TITLE
[CI]: CI failed on Python 3.12

### ISSUE THREAD

**Issue by ktro2828** [tier4/t4-devkit#6]
## What

Exception occurs while installing dependencies as follows:

```shell
...
Run poetry install
Installing dependencies from lock file

Package operations: 64 installs, 0 updates, 0 removals

  - Installing six ([1](https://github.com/tier4/t4-devkit/actions/runs/11136634834/job/30948750053?pr=5#step:5:1).16.0)
  - Installing markupsafe (2.1.5)
  - Installing mergedeep (1.3.4)
  - Installing platformdirs (4.2.2)
  - Installing python-dateutil (2.9.0.post0)
  - Installing pyyaml (6.0.1)
  - Installing click (8.1.7)
  - Installing ghp-import (2.1.0)
  - Installing jinja2 (3.1.4)
  - Installing markdown (3.6)
  - Installing mkdocs-get-deps (0.2.0)
  - Installing packaging (24.1)
  - Installing pathspec (0.[12](https://github.com/tier4/t4-devkit/actions/runs/11136634834/job/30948750053?pr=5#step:5:13).1)
  - Installing pyyaml-env-tag (0.1)
  - Installing watchdog (4.0.1)
  - Installing mkdocs (1.6.0)
  - Installing colorama (0.4.6)
  - Installing cycler (0.12.1)
  - Installing fonttools (4.53.0)
  - Installing kiwisolver (1.4.5)
  - Installing mkdocs-autorefs (1.0.1)
  - Installing numpy (1.26.4)
  - Installing pillow (10.3.0)
  - Installing pymdown-extensions (10.8.1)
  - Installing pyparsing (3.1.2)
  - Installing certifi (2024.7.4)
  - Installing charset-normalizer (3.3.2)
  - Installing griffe (0.47.0)
  - Installing idna (3.7)
  - Installing iniconfig (2.0.0)
  - Installing joblib (1.4.2)
  - Installing matplotlib (3.5.3)
  - Installing mkdocstrings (0.25.1)
  - Installing pluggy (1.5.0)
  - Installing scipy (1.14.0)
  - Installing termcolor (2.4.0)
  - Installing threadpoolctl (3.5.0)
  - Installing urllib3 (2.2.2)
  - Installing attrs (23.2.0)
  - Installing babel (2.15.0)
  - Installing cachetools (5.3.3)
  - Installing descartes (1.1.0)
  - Installing fire (0.6.0)
  - Installing mkdocs-material-extensions (1.3.1)
  - Installing mkdocstrings-python (1.10.5)
  - Installing opencv-python (4.10.0.84)
  - Installing paginate (0.5.6)
  - Installing pyarrow (16.1.0)
  - Installing pycocotools (2.0.8)
  - Installing pygments (2.18.0)
  - Installing pyquaternion (0.9.9)
  - Installing pytest (8.2.2)
  - Installing regex (2024.5.15)
  - Installing requests (2.32.3)
  - Installing scikit-learn (1.5.0)
  - Installing shapely (1.8.5.post1)
  - Installing tqdm (4.66.4)
  - Installing typing-extensions (4.12.2)

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/home/runner/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
    File "/home/runner/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line [13](https://github.com/tier4/t4-devkit/actions/runs/11136634834/job/30948750053?pr=5#step:5:14)7, in get_requires_for_build_wheel
      backend = _build_backend()
                ^^^^^^^^^^^^^^^^
    File "/home/runner/.local/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 70, in _build_backend
      obj = import_module(mod_path)
            ^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.12.6/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 995, in exec_module
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "/tmp/tmp796pwh4y/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line [16](https://github.com/tier4/t4-devkit/actions/runs/11136634834/job/30948750053?pr=5#step:5:17), in <module>
      import setuptools.version
    File "/tmp/tmp796pwh4y/.venv/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
      import pkg_resources
    File "/tmp/tmp796pwh4y/.venv/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
      register_finder(pkgutil.ImpImporter, find_on_path)
                      ^^^^^^^^^^^^^^^^^^^
  AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
  

  at ~/.local/lib/python3.10/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with shapely (1.8.5.post1) not supporting PEP 5[17](https://github.com/tier4/t4-devkit/actions/runs/11136634834/job/30948750053?pr=5#step:5:18) builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "shapely (==1.8.5.post1)"'.
```

**Comment by ktro2828** [comment]
It looks that this error is caused by `shapely<2.0.0`:

```shell
Note: This error originates from the build backend, and is likely not a problem with poetry but with shapely (1.8.5.post1) not supporting PEP 5[17](https://github.com/tier4/t4-devkit/actions/runs/11136634834/job/30948750053?pr=5#step:5:18) builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "shapely (==1.8.5.post1)"'.
```

As far as I experimented with `shapely>2.0.0` in Python 3.12 environment, no error was raised.
